apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "webapp.name" . | default "webapp" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
